name: ingeborgsrealm
favicon: null
layout_spectrum: 0.8209116791840643
typography_spectrum: 0.02654872671701014
title: "Ingeborg's Art"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f0f4'
    - '#0052c0'
    - '#dd2832'
    - '#ffb655'
    - '#7b655e'
  brandStrength: 0.6875
  lightness: 0.7913905631285161
  saturation: 0.794013787060976
  rhythmicContrast: 0.5
purpose: []
