name: ingeborgsrealm
favicon: null
layout_spectrum: 0.8209116791840643
typography_spectrum: 0.02654872671701014
title: "Ingeborg's Art"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6525182456243783
  lightness: 0.7913905631285161
  saturation: 0.794013787060976
  rhythmicContrast: 0.1521685067564249
purpose: []
